# Generated by Django 3.1.2 on 2020-10-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='x',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='y',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
